[project]
name = "when2meet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black==24.10.0",
]

[tool.black]
line-length = 110 

[dependency-groups]
dev = [
    "ruff==0.8.2",
]

[tool.ruff]
target-version = 'py313'